# version: '3'

# services:
#   zookeeper:
#     image: wurstmeister/zookeeper
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#   kafka:
#     image: wurstmeister/kafka
#     container_name: kafka
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ADVERTISED_HOST_NAME: localhost
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9091:9091"
      - "9991:9991"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_PORT=9991
      - KAFKA_JMX_HOSTNAME=localhost

  # kafka2:
  #   image: wurstmeister/kafka
  #   container_name: kafka2
  #   ports:
  #     - "9092:9092"
  #     - "9992:9992"
  #   environment:
  #     - KAFKA_BROKER_ID=2
  #     - KAFKA_ADVERTISED_HOST_NAME=localhost
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_JMX_PORT=9992
  #     - KAFKA_JMX_HOSTNAME=localhost

  # kafka3:
  #   image: wurstmeister/kafka
  #   container_name: kafka3
  #   ports:
  #     - "9093:9093"
  #     - "9993:9993"
  #   environment:
  #     - KAFKA_BROKER_ID=3
  #     - KAFKA_ADVERTISED_HOST_NAME=localhost
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_JMX_PORT=9993
  #     - KAFKA_JMX_HOSTNAME=localhost
     




# version: '2'
# services:

#   broker:
#     image: confluentinc/cp-kafka:7.5.0
#     hostname: broker
#     container_name: broker
#     ports:
#       - "9092:9092"
#       - "9101:9101"
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
#       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_JMX_PORT: 9101
#       KAFKA_JMX_HOSTNAME: localhost